source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'WeexPluginLoader'
	pod 'NatVideo'
end

target 'WeexNatMediaVideo' do
    common
end


